import React from 'react'

const Nirma = () => {
  return (
    <>
       <div class="ishika">
        <div class="row">
            <div class="column">
                <h1 class="DEHEAD">Nirma Institute of Technology</h1>
                <h3 class="DEHEAD1">Ahmedabad, Gujarat</h3>
            </div>

            <div class="column">

                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                            class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://images.indianexpress.com/2021/02/NIrma-A-1200.jpg" height="580px"
                                class="d-block w-100" alt="..."/>
                        </div>
                        <div class="carousel-item">
                            <img src="https://images.shiksha.com/mediadata/images/1495706585php42bFdE.jpeg"
                                height="580px" class="d-block w-100" alt="..."/>
                        </div>
                        <div class="carousel-item">
                            <img src="https://nirmawebsite.s3.ap-south-1.amazonaws.com/wp-content/uploads/sites/22/2019/05/aces.png"
                                height="580px" class="d-block w-100" alt="..." />
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

            <div class="CON">
                <p>
                    At Institute of Technology, quality education is more than a philosophy; it is the very essence of
                    its
                    existence.
                </p>
                <p>
                    Institute of Technology is a leading institute offering multi disciplinary postgraduate &
                    undergraduate
                    programmes in engineering. The institute was Gujarat University till April 2003. Thereafter, it has
                    become a constituent of the Nirma University.
                </p>
                <p>
                    Located in peaceful and sylvan surroundings, about 15 km from Ahmedabad, it is also easily
                    accessible
                    from the state capital Gandhinagar. A disciplined, serene and pleasant environment envelops the
                    campus.
                    It blends beautifully with the green landscaping, aesthetic elegance of arches and the vibrant
                    pursuit
                    of knowledge by the young aspirants. The academic ambience gives full scope for group activities,
                    which
                    are plenty, as also to individual pursuits for development on preferred tracks.
                </p>
                <p>
                    The institute shares the Nirma University campus with four other institutions viz Management,
                    Pharmacy,
                    Science and Diploma Studies. All have distinguished record of achievements. Students joining the
                    Institute of Technology have therefore, an opportunity of interaction with the academic community of
                    the
                    entire Nirma University complex. The academic environment generated by the interaction between
                    professional disciplines has a stimulating influence, especially in the formative years of young
                    students. Exposure to such environment helps the students to develop good communication skills, an
                    integrated personality and greater competitive spirit.
                </p>
                <p>
                    The dedication and commitment with which the students and faculty have worked over the past ten
                    years
                    have paid rich dividends and this has made this institute the most preferred one among the student
                    fraternity. The students of this institute have so far been consistently securing top ranks in
                    Gujarat
                    University examinations. The performance of a student in the examinations is not the sole criterion
                    of
                    the quality of education acquired, nevertheless, it is an important indication of the effectiveness
                    of
                    the academic inputs.
                </p>
                <p>
                    The dedication and commitment with which the students and faculty have worked over the past ten
                    years
                    have paid rich dividends and this has made this institute the most preferred one among the student
                    fraternity. The students of this institute have so far been consistently securing top ranks in
                    Gujarat
                    University examinations. The performance of a student in the examinations is not the sole criterion
                    of
                    the quality of education acquired, nevertheless, it is an important indication of the effectiveness
                    of
                    the academic inputs.
                </p>
                Source: <a href="https://nirmauni.ac.in/">https://nirmauni.ac.in/</a>
            </div>
            <div class="CON">
                <h2 class="DEHEAD3">Cutoff Information:</h2>
                <br/>
                <table border="4" class="able table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2">Course</th>
                            <th colspan="4">Closing Rank</th>
                        </tr>
                        <tr>
                            <th> General Category </th>
                            <th> EBC </th>
                            <th> ST </th>
                            <th> SC </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Computer Engineering</td>
                            <td>336</td>
                            <td>603</td>
                            <td>2139</td>
                            <td>11523</td>
                        </tr>
                        <tr>
                            <td>Civil Engineering</td>
                            <td>11328</td>
                            <td>13623</td>
                            <td>23149</td>
                            <td>34233</td>
                        </tr>
                        <tr>
                            <td>Electrical Engineering</td>
                            <td>7843</td>
                            <td>9000</td>
                            <td>13756</td>
                            <td>24660</td>
                        </tr>
                        <tr>
                            <td>Mechanical Engineering</td>
                            <td>5040</td>
                            <td>7315</td>
                            <td>12534</td>
                            <td>25640</td>
                        </tr>
                        <tr>
                            <td>Chemical Engineering</td>
                            <td>5528</td>
                            <td>8286</td>
                            <td>24910</td>
                            <td>27060</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="main">
                <div class="contain">
                    <h2 class="DEHEAD3">Placement Information:</h2>
                    <br/>
                    <table border="4" class="able table-bordered">
                        <tr>
                            <th>Course</th>
                            <th>No. of Offers</th>
                        </tr>
                        <tr>
                            <td>Computer Engineering</td>
                            <td>353</td>
                        </tr>
                        <tr>
                            <td>Civil Engineering</td>
                            <td>39</td>
                        </tr>
                        <tr>
                            <td>Electrical Engineering</td>
                            <td>120</td>
                        </tr>
                        <tr>
                            <td>Mechanical Engineering</td>
                            <td>140</td>
                        </tr>
                        <tr>
                            <td>Chemical Engineering</td>
                            <td>48</td>
                        </tr>

                    </table>
                </div>
                <div class="CON3">
                    <h5>Placement Year : 2022-2023</h5>
                    <h5>No. of Students placed : 700</h5>
                    <h5>Highest Package : 51.5LPA</h5>
                    <h5>Average Package : 15.7LPA</h5>
                </div>
            </div>

            <div class="CON">
                <h5>Address : </h5>
                <h6 class="DEHEAD1">
                    Nirma University<br/>
                    S G Highway <br/>
                    Ahmedabad ,382481<br/>
                    GUJARAT INDIA<br/>
                </h6>
                <h6>
                    Phone No: +91-79-71652000
                </h6>
                <h6>
                    Email: <a href="placement.ipnu@nirmauni.ac.in"> placement.ipnu@nirmauni.ac.in</a>
                </h6>
            </div>
                </div>
                </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
  </>
  )
}

export default Nirma